FROM node:22

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --include=dev

COPY . .

RUN npm run build

ENV PORT=3334

EXPOSE 3334

CMD ["sh", "-c", "npm run migration:run && npm run dashboard:setup && node dist/index.js"]
